name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  workflow_dispatch:

env:
  token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Run script
      run: deno run -WNE scripts/fetchContributors.ts

    - uses: actions/upload-artifact@v4
      with:
         name: contributors.json
         path: contributors.json

    - name: Commit and push if it changed
      if: github.repository == 'Vanilla-OS/.github' && github.ref == 'refs/heads/main'
      continue-on-error: true
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git add .
        git commit -m "chore: auto-update contributors list"
        git push
